# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Print Env
        run: pwd
      - name: Print Working Directory
        run: ls -la
      - name: Deploy Web Console To Server
        run: echo -e ${{ secrets.TEST }} > /tmp/test
      - name: Echo Test
        run: cat /tmp/test
      
